jobs:
- job: Windows_baseline
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: build/azure-pipelines/win32/continuous-build-win32.yml

- job: Windows_yc
  variables:
    CACHE_YARN: 'True'
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: build/azure-pipelines/win32/continuous-build-win32.yml

- job: Windows_nm
  variables:
    CACHE_NODE_MODULES: 'True'
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: build/azure-pipelines/win32/continuous-build-win32.yml

- job: Windows_yc_nm
  variables:
    CACHE_YARN: 'True'
    CACHE_NODE_MODULES: 'True'
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: build/azure-pipelines/win32/continuous-build-win32.yml

- job: WindowsPrivate
  pool:
    name: jerick-normal
  steps:
  - template: build/azure-pipelines/win32/continuous-build-win32.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build/azure-pipelines/linux/continuous-build-linux.yml

# - job: macOS
#   pool:
#     vmImage: macOS 10.13
#   steps:
#   - template: build/azure-pipelines/darwin/continuous-build-darwin.yml