jobs:
- job: vscode
  variables:
    MATRIX_SALT: 1
    RUN_SALT: 0
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
    BASH_YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
    POOL: Hosted VS2017
  strategy:
    matrix:
      baseline:
        BASH_YARN_CACHE_FOLDER: /d/a/1/yarn-cache
      yc:
        BASH_YARN_CACHE_FOLDER: /d/a/1/yarn-cache
        CACHE_YARN: FILES
      yc_tar:
        BASH_YARN_CACHE_FOLDER: /d/a/1/yarn-cache
        CACHE_YARN: TAR
      nm:
        BASH_YARN_CACHE_FOLDER: /d/a/1/yarn-cache
        CACHE_NODE_MODULES: FILES
      nm_tar:
        BASH_YARN_CACHE_FOLDER: /d/a/1/yarn-cache
        CACHE_NODE_MODULES: TAR
      yc_nm:
        BASH_YARN_CACHE_FOLDER: /d/a/1/yarn-cache
        CACHE_YARN: FILES
        CACHE_NODE_MODULES: FILES
      yctar_nmtar:
        BASH_YARN_CACHE_FOLDER: /d/a/1/yarn-cache
        CACHE_YARN: TAR
        CACHE_NODE_MODULES: TAR
        RUN_SALT: 1
      linux_baseline:
        POOL: Hosted Ubuntu 1604
        BASH_YARN_CACHE_FOLDER:
      linux_nm:
        CACHE_NODE_MODULES: FILES
        POOL: Hosted Ubuntu 1604
      osx_baseline:
        POOL: Hosted macOS
      osx_nm:
        CACHE_NODE_MODULES: FILES
        POOL: Hosted macOS
  pool:
    name: $(POOL)
  steps:
  - template: build/azure-pipelines/win32/continuous-build-win32.yml

# - job: WindowsPrivate
#   pool:
#     name: jerick-normal
#   steps:
#   - template: build/azure-pipelines/win32/continuous-build-win32.yml

# - job: Linux
#   pool:
#     vmImage: 'Ubuntu-16.04'
#   steps:
#   - template: build/azure-pipelines/linux/continuous-build-linux.yml

# - job: macOS
#   pool:
#     vmImage: macOS 10.13
#   steps:
#   - template: build/azure-pipelines/darwin/continuous-build-darwin.yml