jobs:
- job: Windows
  variables:
    MATRIX_SALT: 0
    RUN_SALT: 0
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
    BASH_YARN_CACHE_FOLDER: /d/a/1/yarn-cache

  strategy:
    matrix:
      baseline: {}
      yc:
        CACHE_YARN: FILES
      nm:
        CACHE_NODE_MODULES: FILES
      tar:
        CACHE_NODE_MODULES: TAR
      yc_nm:
        CACHE_YARN: FILES
        CACHE_NODE_MODULES: FILES
      yctar_nmtar:
        CACHE_YARN: TAR
        CACHE_NODE_MODULES: TAR
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: build/azure-pipelines/win32/continuous-build-win32.yml

# - job: WindowsPrivate
#   pool:
#     name: jerick-normal
#   steps:
#   - template: build/azure-pipelines/win32/continuous-build-win32.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: build/azure-pipelines/linux/continuous-build-linux.yml

# - job: macOS
#   pool:
#     vmImage: macOS 10.13
#   steps:
#   - template: build/azure-pipelines/darwin/continuous-build-darwin.yml